{% set name = "odbc2parquet" %}
{% set version = "3.1.0" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pacman82/odbc2parquet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7de3571eae5744fd6ac28bcc03a025d5abbd4cc30eb68afbb4811d7681e83d67

build:
  number: {{ build_num }}
  script:
    - RUSTFLAGS="-Clink-args=-Wl,-L$PREFIX/lib" cargo install --path . --root "$PREFIX"  # [unix]
    - cargo install --path . --root "%LIBRARY_PREFIX%"                                   # [win]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ compiler('c') }}       # [unix]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - unixodbc                  # [unix]
    - libiconv                  # [osx]

test:
  commands:
    - odbc2parquet --help

about:
  home: https://github.com/pacman82/odbc2parquet
  license: MIT
  license_family: MIT
  license_file:
    - License
    - THIRDPARTY.yml
  summary: A command line tool to query an ODBC data source and write the result into a parquet file.
  dev_url: https://github.com/pacman82/odbc2parquet

extra:
  recipe-maintainers:
    - jonashaag
    - pacman82
